# 3.platformName
platformName: 'Android'

# 4.platformVesion
platfromVersion: '10'

# 5.deviceName
deviceName: 'huawei'

# 6.启动程序的报名 appPackage
appPackage: 'com.gemini.cloud.client'

# 7.启动界面名appActivity
appActivity: 'com.gemini.cloud.client.activity.LauncherActivity'

#解决中文
unicodeKeyboard: True
resetKeyboard:  True


#启动app时不要清除app里的原有的数据
noReset: True

# 获取toast automationName = uiautomator2
automationName: 'uiautomator2'
